run:
  go: '1.23.1'
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: false
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - asciicheck
    - bidichk
    - decorder
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - forbidigo
    - forcetypeassert
    - goimports
    - goconst
    - gofmt
    - goheader
    # - gosec
    - grouper
    - importas
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - predeclared
    - promlinter
    - unconvert
    - whitespace
linters-settings:
  gocyclo:
    min-complexity: 18
  # gosec:
  #   excludes:
  #     - G404
  gocritic:
    disabled-checks:
      - regexpMust
      - commentedOutCode
      - docStub
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    settings:
      captLocal:
        paramsOnly: false
      elseif:
        skipBalanced: false
      nestingReduce:
        bodyWidth: 4
      rangeValCopy:
        sizeThreshold: 64
        skipTestFuncs: false
      tooManyResultsChecker:
        maxResults: 100
      truncateCmp:
        skipArchDependent: false
      underef:
        skipRecvDeref: false
      unnamedResult:
        checkExported: true
      hugeParam:
        sizeThreshold: 64