version: "3.7"

networks:
  topchain:

services:
  val-alice:
    command: start
    container_name: val-alice
    image: topchain-node
    volumes:
      - ${HOME}/topchain-devnet/val-alice:/root/.topchain
    networks:
      - topchain

  val-bob:
    command: start
    container_name: val-bob
    image: topchain-node
    volumes:
      - ${HOME}/topchain-devnet/val-bob:/root/.topchain
    networks:
      - topchain

  node-carol:
    command: start
    container_name: node-carol
    image: topchain-node
    volumes:
      - ${HOME}/topchain-devnet/node-carol:/root/.topchain
    ports:
      - 0.0.0.0:26657:26657
    networks:
      - topchain
