version: "3.7"

networks:
  mandu:

services:
  val-alice:
    command: start
    container_name: val-alice
    image: mandu-node
    volumes:
      - ${HOME}/mandu-devnet/val-alice:/root/.mandu
    networks:
      - mandu

  val-bob:
    command: start
    container_name: val-bob
    image: mandu-node
    volumes:
      - ${HOME}/mandu-devnet/val-bob:/root/.mandu
    networks:
      - mandu

  node-carol:
    command: start
    container_name: node-carol
    image: mandu-node
    volumes:
      - ${HOME}/mandu-devnet/node-carol:/root/.mandu
    ports:
      - 0.0.0.0:26657:26657
    networks:
      - mandu
