# https://github.com/golangci/golangci-lint-action

name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: go mod tidy
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.0
          args: --verbose --timeout 5m